dist: bionic
matrix:
  include:
    - language: java
      jdk:
        - openjdk9
      before_install:
        - sudo apt-get install -y zookeeper-server
      install:
        - cd java/dubbo-demo
        - mvn clean install
        - cd dubbo-demo-provider
        - mvn clean package
      before_script:
        - 'sudo service zookeeper-server init'
        - 'sudo service zookeeper-server start'
      script:
        - cd java/dubbo-demo/dubbo-demo-provider
        - java -jar target/dubbo-demo-provider-2.6.3-jar-with-dependencies.jar
      after_script:
        - 'sudo service zookeeper-server stop'
    - language: node_js
      node_js:
        - v10.15.3
      before_install:
        - yarn global add lerna
      install:
        - lerna bootstrap
      before_script:
        - make build-dubbo
        - make build-interpret-util
        - make build-dubbo-invoker
      script:
        - yarn test
notifications:
  email: false
