dist: bionic
matrix:
  include:
    - language: java
      jdk:
        - openjdk9
      before_script:
        - docker pull zookeeper
        - chmod 755 ./start_dubbo_service.sh
      script:
        - ./start_dubbo_service.sh
    - language: node_js
      node_js:
        - v8.12.0
      before_install:
        - npm install -g yarn lerna
      install:
        - lerna bootstrap
      before_script:
        - make build-dubbo
        - make build-interpret-util
        - make build-dubbo-invoker
      script:
        - yarn test
notifications:
  email: false
