dist: bionic
matrix:
  include:
    - language: java
      jdk:
        - openjdk9
      install:
        - cd java/dubbo-demo
        - mvn clean install
        - cd dubbo-demo-provider
        - mvn clean package
      before_script:
        - docker-compose up
      script:
        - cd java/dubbo-demo/dubbo-demo-provider
        - java -jar target/dubbo-demo-provider-2.6.3-jar-with-dependencies.jar
      after_script:
        - docker-compose stop
    - language: node_js
      node_js:
        - v8.12.0
      before_install:
        - npm install -g yarn bootstrap
      install:
        - lerna bootstrap
      before_script:
        - make build-dubbo
        - make build-interpret-util
        - make build-dubbo-invoker
      script:
        - yarn test
notifications:
  email: false
